# Power Management Profiles for Intel NPU

# Power profiles for different usage scenarios
power_profiles:
  
  # Maximum performance - highest power consumption
  performance:
    description: "Maximum performance mode for demanding workloads"
    npu_frequency: "max"
    thermal_limit: 85  # Celsius
    power_limit: "15W"
    
    # OpenVINO settings
    openvino:
      PERFORMANCE_HINT: "THROUGHPUT"
      INFERENCE_PRECISION_HINT: "f16"
      
    # Audio processing
    audio:
      chunk_size: 2048
      overlap: 0.5
      preprocessing: "full"
      
    # Model settings
    models:
      precision: "FP16"
      batch_size: 1
      
  # Balanced performance and power
  balanced:
    description: "Balanced performance and power consumption"
    npu_frequency: "balanced"
    thermal_limit: 75
    power_limit: "10W"
    
    openvino:
      PERFORMANCE_HINT: "LATENCY"
      INFERENCE_PRECISION_HINT: "f16"
      
    audio:
      chunk_size: 1024
      overlap: 0.3
      preprocessing: "essential"
      
    models:
      precision: "FP16"
      batch_size: 1
      
  # Power saving mode - lowest consumption
  power_saver:
    description: "Power saving mode for battery devices"
    npu_frequency: "eco"
    thermal_limit: 65
    power_limit: "5W"
    
    openvino:
      PERFORMANCE_HINT: "LATENCY"
      INFERENCE_PRECISION_HINT: "f16"
      
    audio:
      chunk_size: 512
      overlap: 0.1
      preprocessing: "minimal"
      
    models:
      precision: "INT8"  # Use quantized models
      batch_size: 1
      
  # Custom profiles for specific scenarios
  realtime:
    description: "Optimized for real-time streaming"
    npu_frequency: "high"
    thermal_limit: 80
    power_limit: "12W"
    
    openvino:
      PERFORMANCE_HINT: "LATENCY"
      INFERENCE_PRECISION_HINT: "f16"
      
    audio:
      chunk_size: 1024
      overlap: 0.2
      preprocessing: "stream_optimized"
      buffer_size: "small"
      
    models:
      precision: "FP16"
      batch_size: 1
      preload_models: true
      
  # Battery optimized for laptops
  battery:
    description: "Optimized for battery-powered devices"
    npu_frequency: "adaptive"
    thermal_limit: 70
    power_limit: "8W"
    
    openvino:
      PERFORMANCE_HINT: "LATENCY"
      INFERENCE_PRECISION_HINT: "f16"
      
    audio:
      chunk_size: 512
      overlap: 0.1
      preprocessing: "minimal"
      
    models:
      precision: "INT8"
      batch_size: 1
      adaptive_loading: true

# Thermal management settings
thermal_management:
  # Temperature thresholds
  warning_temp: 75    # Start reducing performance
  critical_temp: 85   # Emergency throttling
  safe_temp: 65      # Normal operation
  
  # Throttling behavior
  throttling:
    enabled: true
    step_size: 10      # Percentage reduction per step
    check_interval: 5   # seconds
    recovery_hysteresis: 5  # degrees for recovery
    
  # Cooling strategies
  cooling:
    passive_cooling: true
    adaptive_frequency: true
    workload_reduction: true

# Power monitoring
power_monitoring:
  # Monitoring intervals
  sample_interval: 1.0  # seconds
  log_interval: 30.0    # seconds
  
  # Thresholds
  power_warning: "12W"
  power_critical: "15W"
  
  # Actions
  auto_profile_switching: true
  emergency_shutdown: false

# Battery optimization (for mobile/laptop deployment)
battery_optimization:
  # Battery level thresholds
  high_battery: 80     # Use performance profile
  medium_battery: 50   # Use balanced profile  
  low_battery: 20      # Use power_saver profile
  critical_battery: 10 # Minimal processing
  
  # Adaptive behavior
  adaptive_profiles: true
  battery_aware_scheduling: true
  
  # Power saving features
  suspend_on_idle: true
  idle_timeout: 300    # seconds
  reduce_polling: true