version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: livetranslate-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: livetranslate
      POSTGRES_USER: livetranslate
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-livetranslate_dev_password}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      # Persistent data
      - postgres_data:/var/lib/postgresql/data
      # Initialization scripts
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/01-init-db.sql:ro
      - ./scripts/bot-sessions-schema.sql:/docker-entrypoint-initdb.d/02-bot-sessions-schema.sql:ro
      # Configuration
      - ./docker/postgres/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./docker/postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
    command: 
      - postgres
      - -c
      - config_file=/etc/postgresql/postgresql.conf
    networks:
      - livetranslate-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U livetranslate -d livetranslate"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:7-alpine
    container_name: livetranslate-redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - livetranslate-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: livetranslate-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@livetranslate.local}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "${PGADMIN_PORT:-8080}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json:ro
    networks:
      - livetranslate-network
    depends_on:
      postgres:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"

volumes:
  postgres_data:
    driver: local
    name: livetranslate_postgres_data
  redis_data:
    driver: local
    name: livetranslate_redis_data
  pgadmin_data:
    driver: local
    name: livetranslate_pgadmin_data

networks:
  livetranslate-network:
    name: livetranslate-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16