"""Add all missing tables and indexes

Revision ID: 5f3bcf8a26da
Revises: 001_initial
Create Date: 2026-01-16 18:40:26.877551

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5f3bcf8a26da"
down_revision = "001_initial"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "domain_categories",
        sa.Column("domain_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column("success_rate", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("domain_id"),
    )
    op.create_index("ix_domain_categories_active", "domain_categories", ["is_active"], unique=False)
    op.create_index(op.f("ix_domain_categories_name"), "domain_categories", ["name"], unique=True)
    op.create_index(
        "ix_domain_categories_usage", "domain_categories", ["usage_count"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("max_concurrent_sessions", sa.Integer(), server_default="10", nullable=False),
        sa.Column("preferred_language", sa.String(length=10), nullable=True),
        sa.Column(
            "preferences",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("jsonb('{}')"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_active_at", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index("ix_users_created_at", "users", ["created_at"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index("ix_users_last_active", "users", ["last_active_at"], unique=False)
    op.create_index(
        "ix_users_preferences_gin", "users", ["preferences"], unique=False, postgresql_using="gin"
    )
    op.create_index(op.f("ix_users_user_id"), "users", ["user_id"], unique=False)
    op.create_table(
        "api_tokens",
        sa.Column("token_id", sa.UUID(), nullable=False),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("scopes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("token_id"),
    )
    op.create_index("ix_api_tokens_expires_at", "api_tokens", ["expires_at"], unique=False)
    op.create_index(op.f("ix_api_tokens_token"), "api_tokens", ["token"], unique=True)
    op.create_index(op.f("ix_api_tokens_user_id"), "api_tokens", ["user_id"], unique=False)
    op.create_table(
        "conversation_sessions",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("session_type", sa.String(length=50), nullable=False),
        sa.Column("session_title", sa.String(length=500), nullable=True),
        sa.Column("started_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("last_message_at", sa.DateTime(), nullable=True),
        sa.Column("target_languages", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("enable_translation", sa.Boolean(), nullable=False),
        sa.Column("message_count", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("session_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_index(
        "ix_conv_sessions_last_message_at",
        "conversation_sessions",
        ["last_message_at"],
        unique=False,
    )
    op.create_index(
        "ix_conv_sessions_metadata_gin",
        "conversation_sessions",
        ["session_metadata"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_conv_sessions_session_type", "conversation_sessions", ["session_type"], unique=False
    )
    op.create_index(
        "ix_conv_sessions_started_at", "conversation_sessions", ["started_at"], unique=False
    )
    op.create_index(
        "ix_conv_sessions_user_started",
        "conversation_sessions",
        ["user_id", "started_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_sessions_user_id"), "conversation_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "domain_prompts",
        sa.Column("prompt_id", sa.UUID(), nullable=False),
        sa.Column("domain_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("template", sa.Text(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("max_tokens", sa.Integer(), nullable=False),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column("average_quality_score", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["domain_id"],
            ["domain_categories.domain_id"],
        ),
        sa.PrimaryKeyConstraint("prompt_id"),
    )
    op.create_index("ix_domain_prompts_default", "domain_prompts", ["is_default"], unique=False)
    op.create_index("ix_domain_prompts_domain", "domain_prompts", ["domain_id"], unique=False)
    op.create_index("ix_domain_prompts_usage", "domain_prompts", ["usage_count"], unique=False)
    op.create_table(
        "domain_terminology",
        sa.Column("term_id", sa.UUID(), nullable=False),
        sa.Column("domain_id", sa.UUID(), nullable=False),
        sa.Column("term", sa.String(length=255), nullable=False),
        sa.Column("normalized_term", sa.String(length=255), nullable=False),
        sa.Column("phonetic", sa.String(length=255), nullable=True),
        sa.Column("common_context", sa.Text(), nullable=True),
        sa.Column("alternatives", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("importance", sa.Integer(), nullable=False),
        sa.Column("frequency", sa.Integer(), nullable=False),
        sa.Column("accuracy_improvement", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["domain_id"],
            ["domain_categories.domain_id"],
        ),
        sa.PrimaryKeyConstraint("term_id"),
    )
    op.create_index(
        "ix_domain_terminology_domain_importance",
        "domain_terminology",
        ["domain_id", "importance"],
        unique=False,
    )
    op.create_index(
        "ix_domain_terminology_importance", "domain_terminology", ["importance"], unique=False
    )
    op.create_index(
        "ix_domain_terminology_normalized", "domain_terminology", ["normalized_term"], unique=False
    )
    op.create_index("ix_domain_terminology_term", "domain_terminology", ["term"], unique=False)
    op.create_table(
        "user_domain_preferences",
        sa.Column("preference_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("domain_id", sa.UUID(), nullable=False),
        sa.Column("custom_terminology", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("custom_prompt_template", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["domain_id"],
            ["domain_categories.domain_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("preference_id"),
    )
    op.create_index(
        "ix_user_domain_prefs_domain", "user_domain_preferences", ["domain_id"], unique=False
    )
    op.create_index(
        "ix_user_domain_prefs_user", "user_domain_preferences", ["user_id"], unique=False
    )
    op.create_index(
        "ix_user_domain_prefs_user_domain",
        "user_domain_preferences",
        ["user_id", "domain_id"],
        unique=True,
    )
    op.create_table(
        "chat_messages",
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("original_language", sa.String(length=10), nullable=True),
        sa.Column("translated_content", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("timestamp", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("edited_at", sa.DateTime(), nullable=True),
        sa.Column("confidence", sa.Integer(), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.Column("message_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["conversation_sessions.session_id"],
        ),
        sa.PrimaryKeyConstraint("message_id"),
    )
    op.create_index(
        "ix_chat_messages_content_fulltext",
        "chat_messages",
        ["content"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"content": "gin_trgm_ops"},
    )
    op.create_index("ix_chat_messages_role", "chat_messages", ["role"], unique=False)
    op.create_index(
        "ix_chat_messages_sequence",
        "chat_messages",
        ["session_id", "sequence_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_messages_session_id"), "chat_messages", ["session_id"], unique=False
    )
    op.create_index("ix_chat_messages_timestamp", "chat_messages", ["timestamp"], unique=False)
    op.create_index(
        "ix_chat_messages_translated_gin",
        "chat_messages",
        ["translated_content"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "conversation_statistics",
        sa.Column("statistics_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("total_messages", sa.Integer(), nullable=False),
        sa.Column("user_messages", sa.Integer(), nullable=False),
        sa.Column("assistant_messages", sa.Integer(), nullable=False),
        sa.Column("total_characters", sa.Integer(), nullable=False),
        sa.Column("total_words", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("languages_used", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("translation_count", sa.Integer(), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("avg_response_time", sa.Integer(), nullable=True),
        sa.Column("average_confidence", sa.Integer(), nullable=True),
        sa.Column("calculated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["conversation_sessions.session_id"],
        ),
        sa.PrimaryKeyConstraint("statistics_id"),
        sa.UniqueConstraint("session_id"),
    )
    op.create_index(
        "ix_conv_stats_calculated_at", "conversation_statistics", ["calculated_at"], unique=False
    )
    op.create_index(
        "ix_conv_stats_session_id", "conversation_statistics", ["session_id"], unique=False
    )
    op.create_table(
        "domain_usage_logs",
        sa.Column("log_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("domain_id", sa.UUID(), nullable=False),
        sa.Column("prompt_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.String(length=255), nullable=True),
        sa.Column("model_used", sa.String(length=100), nullable=False),
        sa.Column("transcription_quality", sa.Integer(), nullable=True),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("terminology_matches", sa.Integer(), nullable=False),
        sa.Column("processing_time_ms", sa.Integer(), nullable=True),
        sa.Column("prompt_tokens_used", sa.Integer(), nullable=True),
        sa.Column("context_tokens_used", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["domain_id"],
            ["domain_categories.domain_id"],
        ),
        sa.ForeignKeyConstraint(
            ["prompt_id"],
            ["domain_prompts.prompt_id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["conversation_sessions.session_id"],
        ),
        sa.PrimaryKeyConstraint("log_id"),
    )
    op.create_index("ix_domain_usage_created", "domain_usage_logs", ["created_at"], unique=False)
    op.create_index("ix_domain_usage_domain", "domain_usage_logs", ["domain_id"], unique=False)
    op.create_index(
        "ix_domain_usage_domain_date",
        "domain_usage_logs",
        ["domain_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_domain_usage_logs_created_at"), "domain_usage_logs", ["created_at"], unique=False
    )
    op.create_index("ix_domain_usage_session", "domain_usage_logs", ["session_id"], unique=False)
    op.alter_column(
        "audio_files",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "bot_sessions",
        "bot_type",
        existing_type=sa.VARCHAR(length=50),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "bot_sessions",
        "status",
        existing_type=sa.VARCHAR(length=50),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "bot_sessions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "bot_sessions",
        "enable_translation",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "bot_sessions",
        "enable_transcription",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "bot_sessions",
        "enable_virtual_webcam",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "bot_sessions",
        "audio_storage_enabled",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.create_index("idx_bot_sessions_bot_id", "bot_sessions", ["bot_id"], unique=False)
    op.create_index("idx_bot_sessions_meeting_id", "bot_sessions", ["meeting_id"], unique=False)
    op.alter_column(
        "glossaries",
        "source_language",
        existing_type=sa.VARCHAR(length=10),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "glossaries",
        "is_active",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "glossaries",
        "is_default",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "glossaries",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "glossaries",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "glossaries",
        "entry_count",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.create_index(op.f("ix_glossaries_domain"), "glossaries", ["domain"], unique=False)
    op.create_index(op.f("ix_glossaries_name"), "glossaries", ["name"], unique=False)
    op.alter_column(
        "glossary_entries",
        "case_sensitive",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "glossary_entries",
        "match_whole_word",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "glossary_entries",
        "priority",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "glossary_entries",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "glossary_entries",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        existing_nullable=False,
    )
    op.create_index(
        op.f("ix_glossary_entries_source_term_normalized"),
        "glossary_entries",
        ["source_term_normalized"],
        unique=False,
    )
    op.create_index("idx_participants_speaker_id", "participants", ["speaker_id"], unique=False)
    op.alter_column(
        "session_events",
        "timestamp",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "session_events",
        "severity",
        existing_type=sa.VARCHAR(length=20),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "session_statistics",
        "total_participants",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "session_statistics",
        "total_audio_files",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "session_statistics",
        "total_transcripts",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "session_statistics",
        "total_translations",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "session_statistics",
        "total_correlations",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "session_statistics",
        "total_words",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "session_statistics",
        "total_characters",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "session_statistics",
        "unique_speakers",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "session_statistics",
        "calculated_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "session_statistics",
        "calculated_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "session_statistics",
        "unique_speakers",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "session_statistics",
        "total_characters",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "session_statistics",
        "total_words",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "session_statistics",
        "total_correlations",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "session_statistics",
        "total_translations",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "session_statistics",
        "total_transcripts",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "session_statistics",
        "total_audio_files",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "session_statistics",
        "total_participants",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "session_events",
        "severity",
        existing_type=sa.VARCHAR(length=20),
        server_default=sa.text("'info'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "session_events",
        "timestamp",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.drop_index("idx_participants_speaker_id", table_name="participants")
    op.drop_index(op.f("ix_glossary_entries_source_term_normalized"), table_name="glossary_entries")
    op.alter_column(
        "glossary_entries",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "glossary_entries",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "glossary_entries",
        "priority",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "glossary_entries",
        "match_whole_word",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_nullable=False,
    )
    op.alter_column(
        "glossary_entries",
        "case_sensitive",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_glossaries_name"), table_name="glossaries")
    op.drop_index(op.f("ix_glossaries_domain"), table_name="glossaries")
    op.alter_column(
        "glossaries",
        "entry_count",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "glossaries",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "glossaries",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "glossaries",
        "is_default",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.alter_column(
        "glossaries",
        "is_active",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_nullable=False,
    )
    op.alter_column(
        "glossaries",
        "source_language",
        existing_type=sa.VARCHAR(length=10),
        server_default=sa.text("'en'::character varying"),
        existing_nullable=False,
    )
    op.drop_index("idx_bot_sessions_meeting_id", table_name="bot_sessions")
    op.drop_index("idx_bot_sessions_bot_id", table_name="bot_sessions")
    op.alter_column(
        "bot_sessions",
        "audio_storage_enabled",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_nullable=False,
    )
    op.alter_column(
        "bot_sessions",
        "enable_virtual_webcam",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("false"),
        existing_nullable=False,
    )
    op.alter_column(
        "bot_sessions",
        "enable_transcription",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_nullable=False,
    )
    op.alter_column(
        "bot_sessions",
        "enable_translation",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_nullable=False,
    )
    op.alter_column(
        "bot_sessions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "bot_sessions",
        "status",
        existing_type=sa.VARCHAR(length=50),
        server_default=sa.text("'pending'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "bot_sessions",
        "bot_type",
        existing_type=sa.VARCHAR(length=50),
        server_default=sa.text("'google_meet'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "audio_files",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.drop_index("ix_domain_usage_session", table_name="domain_usage_logs")
    op.drop_index(op.f("ix_domain_usage_logs_created_at"), table_name="domain_usage_logs")
    op.drop_index("ix_domain_usage_domain_date", table_name="domain_usage_logs")
    op.drop_index("ix_domain_usage_domain", table_name="domain_usage_logs")
    op.drop_index("ix_domain_usage_created", table_name="domain_usage_logs")
    op.drop_table("domain_usage_logs")
    op.drop_index("ix_conv_stats_session_id", table_name="conversation_statistics")
    op.drop_index("ix_conv_stats_calculated_at", table_name="conversation_statistics")
    op.drop_table("conversation_statistics")
    op.drop_index(
        "ix_chat_messages_translated_gin", table_name="chat_messages", postgresql_using="gin"
    )
    op.drop_index("ix_chat_messages_timestamp", table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_session_id"), table_name="chat_messages")
    op.drop_index("ix_chat_messages_sequence", table_name="chat_messages")
    op.drop_index("ix_chat_messages_role", table_name="chat_messages")
    op.drop_index(
        "ix_chat_messages_content_fulltext",
        table_name="chat_messages",
        postgresql_using="gin",
        postgresql_ops={"content": "gin_trgm_ops"},
    )
    op.drop_table("chat_messages")
    op.drop_index("ix_user_domain_prefs_user_domain", table_name="user_domain_preferences")
    op.drop_index("ix_user_domain_prefs_user", table_name="user_domain_preferences")
    op.drop_index("ix_user_domain_prefs_domain", table_name="user_domain_preferences")
    op.drop_table("user_domain_preferences")
    op.drop_index("ix_domain_terminology_term", table_name="domain_terminology")
    op.drop_index("ix_domain_terminology_normalized", table_name="domain_terminology")
    op.drop_index("ix_domain_terminology_importance", table_name="domain_terminology")
    op.drop_index("ix_domain_terminology_domain_importance", table_name="domain_terminology")
    op.drop_table("domain_terminology")
    op.drop_index("ix_domain_prompts_usage", table_name="domain_prompts")
    op.drop_index("ix_domain_prompts_domain", table_name="domain_prompts")
    op.drop_index("ix_domain_prompts_default", table_name="domain_prompts")
    op.drop_table("domain_prompts")
    op.drop_index(op.f("ix_conversation_sessions_user_id"), table_name="conversation_sessions")
    op.drop_index("ix_conv_sessions_user_started", table_name="conversation_sessions")
    op.drop_index("ix_conv_sessions_started_at", table_name="conversation_sessions")
    op.drop_index("ix_conv_sessions_session_type", table_name="conversation_sessions")
    op.drop_index(
        "ix_conv_sessions_metadata_gin", table_name="conversation_sessions", postgresql_using="gin"
    )
    op.drop_index("ix_conv_sessions_last_message_at", table_name="conversation_sessions")
    op.drop_table("conversation_sessions")
    op.drop_index(op.f("ix_api_tokens_user_id"), table_name="api_tokens")
    op.drop_index(op.f("ix_api_tokens_token"), table_name="api_tokens")
    op.drop_index("ix_api_tokens_expires_at", table_name="api_tokens")
    op.drop_table("api_tokens")
    op.drop_index(op.f("ix_users_user_id"), table_name="users")
    op.drop_index("ix_users_preferences_gin", table_name="users", postgresql_using="gin")
    op.drop_index("ix_users_last_active", table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index("ix_users_created_at", table_name="users")
    op.drop_table("users")
    op.drop_index("ix_domain_categories_usage", table_name="domain_categories")
    op.drop_index(op.f("ix_domain_categories_name"), table_name="domain_categories")
    op.drop_index("ix_domain_categories_active", table_name="domain_categories")
    op.drop_table("domain_categories")
    # ### end Alembic commands ###
